### ISSUE TITLE
How to unintall?

### ISSUE THREAD

**Issue by livelazily** [ShikiSuen/OriginHanSansUI#3]
RT

**Comment by ShikiSuen** [comment]
Please use **Yosemite Factorial STHeiti Fallback Recovery Pack**:
https://originhansansui.codeplex.com/releases/view/615922

This package could only be used with OS X Yosemite (only those builds released after Apple Special Event October 2014), it will recover these factorial files:
- Recover all "STHeti-????.ttc" at "C:\System\Library\Fonts\" folder.
- Recover "华文黑体.ttf" and "华文细黑.ttf" at "C:\Library\Fonts\" folder.
- Replace "DefaultFontFallbacks.plist" & "CTPresetFallbacks.plist" by using OS X Yosemite factorial file versions (i.e.: Apple official plist settings regarding Yosemite).

Enjoy.

**Comment by ShikiSuen** [comment]
After that, feel free to manually remove "OriginHanSansUI.ttc", "SourceHanSansUI.ttc", "SHSDeskInterface.ttc", etc.

(Currently, only "OriginHanSansUI.ttc" will be installed by those package released in recent update, other font names are deprecated.)

**Comment by ShikiSuen** [comment]
If you are using El Capitan Dev Preview or Public Seed, the only way is to reinstall your system.

**Comment by livelazily** [comment]
ok, thanks

**Comment by ShikiSuen** [comment]
No Problem.
